behaviors:
    Agent:
        trainer_type: ppo
        hyperparameters:
            batch_size: 2000
            buffer_size: 20000
            num_epoch: 4
        network_settings:
            hidden_units: 300
            num_layers: 2
#            memory:
#                memory_size: 128
#                sequence_length: 8
        reward_signals:
            extrinsic:
                gamma: 0.99
#            curiosity:
#                strength: 0.1
        time_horizon: 300
        max_steps: 1e7
        threaded: true
        summary_freq: 20000
        #checkpoint_interval: 40000
        keep_checkpoints: 100
engine_settings:
  width: 640
  height: 360